DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS shapes;
DROP TABLE IF EXISTS stop_times;

CREATE TABLE routes (
	route_id INT PRIMARY KEY,
	agency_id TEXT,
	route_short_name TEXT,
	route_long_name TEXT,
	route_desc TEXT,
	route_type INT,
	route_url TEXT,
	route_color TEXT,
	route_text_color TEXT
);

CREATE TABLE shapes (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	shape_id INT,
	shape_pt_lat REAL,
	shape_pt_lon REAL,
	shape_pt_sequence INT,
	shape_dist_traveled REAL
);

CREATE TABLE stop_times (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	trip_id INT,
	arrival_time TEXT,
	departure_time TEXT,
	stop_id INT,
	stop_sequence INT,
	stop_headsign INT,
	pickup_type TEXT,
	drop_off_type TEXT,
	shape_dist_traveled REAL
);

CREATE TABLE trips(
	trip_id INT PRIMARY KEY,
	route_id INT REFERENCES routes(route_id),
	service_id VARCHAR,
	trip_headsign VARCHAR,
	trip_short_name VARCHAR,
	direction_id INT,
	block_id INT,
	shape_id INT,
	wheelchair_accessible INT,
	bikes_allowed INT
);