DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS shapes;
DROP TABLE IF EXISTS stop_times;

CREATE TABLE trips(
	trip_id INT PRIMARY KEY,
	route_id INT REFERENCES routes(route_id),
	service_id VARCHAR,
	trip_headsign VARCHAR,
	trip_short_name VARCHAR,
	direction_id INT,
	block_id INT,
	shape_id INT,
	wheelchair_accessible INT,
	bikes_allowed INT
);

COPY trips (
	route_id,
	service_id,
	trip_id,
	trip_headsign,
	trip_short_name,
	direction_id,
	block_id,
	shape_id,
	wheelchair_accessible, 
	bikes_allowed
) 
FROM '/tmp/salem-or-us/trips.txt' WITH DELIMITER ',' CSV HEADER;

CREATE TABLE routes (
	route_id INT PRIMARY KEY,
	agency_id TEXT,
	route_short_name TEXT,
	route_long_name TEXT,
	route_desc TEXT,
	route_type INT,
	route_url TEXT,
	route_color TEXT,
	route_text_color TEXT
);

COPY routes(
	route_id,
	agency_id,
	route_short_name,
	route_long_name,
	route_desc,
	route_type,
	route_url,
	route_color,
	route_text_color)
FROM '/tmp/salem-or-us/routes.txt' WITH DELIMITER ',' CSV HEADER;

CREATE TABLE shapes (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	shape_id INT,
	shape_pt_lat REAL,
	shape_pt_lon REAL,
	shape_pt_sequence INT,
	shape_dist_traveled REAL
);

COPY shapes (
	shape_id,
	shape_pt_lat,
	shape_pt_lon,
	shape_pt_sequence,
	shape_dist_traveled
)
FROM '/tmp/salem-or-us/shapes.txt' WITH DELIMITER ',' CSV HEADER;

CREATE TABLE stop_times (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	trip_id INT,
	arrival_time TEXT,
	departure_time TEXT,
	stop_id INT,
	stop_sequence INT,
	stop_headsign INT,
	pickup_type TEXT,
	drop_off_type TEXT,
	shape_dist_traveled REAL
);

COPY stop_times(
	trip_id,
	arrival_time,
	departure_time,
	stop_id,
	stop_sequence,
	stop_headsign,
	pickup_type,
	drop_off_type,
	shape_dist_traveled
)
FROM '/tmp/salem-or-us/stop_times.txt' WITH DELIMITER ',' CSV HEADER;
