DROP TABLE IF EXISTS trips;

CREATE TABLE trips (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	route_id INT,
	service_id VARCHAR,
	trip_id INT,
	trip_headsign VARCHAR,
	trip_short_name VARCHAR,
	direction_id INT,
	block_id INT,
	shape_id INT,
	wheelchair_accessible INT,
	bikes_allowed INT
);

COPY trips(route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible, bikes_allowed) FROM '/tmp/trips.csv' WITH DELIMITER ',' CSV HEADER;