CREATE TABLE shapes (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	shape_id INT,
	shape_pt_lat NUMERIC(8, 6),
	shape_pt_lon NUMERIC(9, 6),
	shape_pt_sequence INT,
	shape_dist_traveled NUMERIC
);