CREATE TABLE stop_times (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	trip_id INT REFERENCES trips(trip_id),
	arrival_time TEXT,
	departure_time TEXT,
	stop_id INT REFERENCES stops(stop_id),
	stop_sequence INT,
	stop_headsign INT,
	pickup_type TEXT,
	drop_off_type TEXT,
	shape_dist_traveled NUMERIC
);